language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mkdir ./app/storage
  - mkdir /app/storage/cache
  - mkdir /app/storage/logs
  - mkdir /app/storage/meta
  - mkdir /app/storage/sessions
  - mkdir /app/storage/views
  - sudo chmod -R 775 ./app/storage 
  - php -S localhost:8000 -t ./public/ &
  - sleep 5

script: 
  - vendor/bin/behat --config behat-dev.yml
  - phpunit

sudo: required
