language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - mkdir ./app/storage
  - mkdir ./app/storage/cache
  - mkdir ./app/storage/logs
  - mkdir ./app/storage/meta
  - mkdir ./app/storage/sessions
  - mkdir ./app/storage/views
  - chmod -R 775 ./app/storage 
  - mkdir -p ./app/build/logs
  - chmod -R 775 ./app/build

script: 
  - phpunit
  
after_script:
 - php vendor/bin/coveralls -v