language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - chmod 775 app/storage 
  - php -S localhost:8000 -t /home/travis/build/Gadoma/Exapp/public/ &
  - sleep 5

script: 
  - vendor/bin/behat --config behat-dev.yml
  - phpunit

